export const dependenciesData = [
  {
    fileType: "script",
    scope: "public",
    packageName: "vue3",
    fileUrl: "https://cdn.yearrow.com/files/vue/3.4.34/vue.global.prod.js",
  },
  {
    fileType: "script",
    scope: "public",
    packageName: "vue-router",
    fileUrl: "https://cdn.yearrow.com/files/vue-router/4.2.5/vue-router.global.prod.js",
  },
  {
    fileType: "script",
    scope: "public",
    packageName: "axios",
    fileUrl: "https://cdn.yearrow.com/files/axios/1.7.0/axios.min.js",
  },
  {
    fileType: "script",
    scope: "public",
    packageName: "decimal",
    fileUrl: "https://cdn.yearrow.com/files/decimal.js/10.4.3/decimal.js",
  },
  {
    fileType: "script",
    scope: "public",
    packageName: "@antv/g2plot",
    fileUrl: "https://cdn.yearrow.com/files/@antv/g2plot/2.4.32/g2plot.min.js",
  },
  {
    fileType: "style",
    scope: "public",
    packageName: "fonts/cs-common",
    fileUrl: "https://cdn.yearrow.com/fonts/cs-common/1.0.0/iconfont.css",
  },
  {
    fileType: "script",
    scope: "public",
    packageName: "element-plus-js",
    fileUrl: "https://cdn.yearrow.com/files/element-plus/2.13.7/index.full.min.js",
  },
  {
    fileType: "script",
    scope: "public",
    packageName: "@element-plus/icons-vue",
    fileUrl: "https://cdn.yearrow.com/files/@element-plus/icons-vue/2.3.1/global.iife.min.js",
  },
  {
    fileType: "script",
    scope: "public",
    packageName: "@cs/element-plus-ui-js",
    fileUrl: "https://cdn.yearrow.com/files/@cs/element-plus-ui/1.1.0/element-plus-ui.iife.js",
  },
  {
    fileType: "style",
    scope: "public",
    packageName: "@cs/element-plus-ui-css",
    fileUrl: "https://cdn.yearrow.com/files/@cs/element-plus-ui/1.1.0/theme/yun-que.css",
  },
  {
    fileType: "style",
    scope: "public",
    packageName: "@cs/table-pro-css",
    fileUrl: "https://cdn.yearrow.com/files/@cs/table-pro/3.0.3/theme/yun-que.css",
  },
  {
    fileType: "script",
    scope: "public",
    packageName: "@cs/table-pro-js",
    fileUrl: "https://cdn.yearrow.com/files/@cs/table-pro/3.0.3/table-pro.iife.js",
  },
  {
    fileType: "script",
    scope: "public",
    packageName: "js-web-frameworky",
    fileUrl: "https://cdn.yearrow.com/files/@cs/js-web-framework/1.2.0/js-web-framework.umd.js",
  },
  {
    fileType: "script",
    scope: "public",
    packageName: "vue3-biz-components-library",
    fileUrl: "https://cdn.yearrow.com/files/@cs/vue3-biz-components-library/test-2026-8-18/vue3-biz-components-library.umd.js",
  },
  {
    fileType: "script",
    scope: "public",
    packageName: "@cs/better-print",
    fileUrl: "https://cdn.yearrow.com/files/@cs/better-print/1.2.16/better-print.iife.js",
  },
  {
    fileType: "script",
    scope: "public",
    packageName: "@cs/excel-conduct-library",
    fileUrl: "https://cdn.yearrow.com/files/@cs/excel-conduct-library/2.1.19/excel-conduct-library.iife.js",
  },
  {
    fileType: "script",
    scope: "private",
    packageName: "@cs/excel-conduct-library",
    fileUrl: "https://cdn.yearrow.com/files/assem-component/desktop/test-yanshi-receive/1.0.3/lib/assembox-renderer-test-yanshi-receive.umd.js",
  },
];
