import type { ComponentCatalogItem } from "../../../scenario/types";
import {
  modelNameProp,
  reloadClearMethods,
  SIZE_ENUM,
} from "./shared";

/**
 * 业务组件（源码：components/business-component/）
 * 依赖 @cs/vue3-biz-components-library / @cs/js-file-client-library 等宿主库
 */
export const businessComponents: ComponentCatalogItem[] = [
  {
    renderType: "YqBasisCommonSelectApi",
    name: "通用 API 下拉",
    group: "business",
    category: "select",
    scaffold: { renderType: "YqBasisCommonSelectApi", requestConfig: { url: "", searchField: "", conditionItems: [], params: {} }, defaultProps: { label: "label", value: "value" }, limit: 20, width: "", dropdownWidth: "", dropdownHeight: "", clearable: true, placeholder: "请选择", searchPlaceholder: "输入关键词搜索", disabled: false, searchEnable: true, size: "", downloadCode: "", defaultText: "", modelName: "" },
    props: [
      { name: "requestConfig", title: "请求配置（url/搜索字段/条件）", propType: "json", defaultValue: { url: "", searchField: "", conditionItems: [], params: {} } },
      { name: "defaultProps", title: "字段映射", propType: "json", defaultValue: { label: "label", value: "value" } },
      { name: "limit", title: "返回条数上限", propType: "number", defaultValue: 20 },
      { name: "width", title: "宽度", propType: "string", defaultValue: "" },
      { name: "dropdownWidth", title: "下拉宽度", propType: "string", defaultValue: "" },
      { name: "dropdownHeight", title: "下拉高度", propType: "string", defaultValue: "" },
      { name: "clearable", title: "可清空", propType: "boolean", defaultValue: true },
      { name: "placeholder", title: "占位文本", propType: "string", defaultValue: "请选择" },
      { name: "searchPlaceholder", title: "搜索占位", propType: "string", defaultValue: "输入关键词搜索" },
      { name: "disabled", title: "禁用", propType: "boolean", defaultValue: false },
      { name: "searchEnable", title: "启用搜索", propType: "boolean", defaultValue: true },
      { name: "size", title: "尺寸", propType: SIZE_ENUM, defaultValue: "" },
      { name: "downloadCode", title: "下载编码", propType: "string", defaultValue: "" },
      { name: "defaultText", title: "默认显示文本", propType: "string", defaultValue: "" },
      modelNameProp(),
    ],
    events: [
      { name: "onMounted", title: "挂载后" },
      { name: "onChange", title: "值变化" },
      { name: "onClear", title: "清空" },
      { name: "onReload", title: "刷新" },
      { name: "onDownloadSuccess", title: "下载成功" },
      { name: "onValueRender", title: "值渲染" },
    ],
    methods: [
      ...reloadClearMethods(),
      { name: "getNativeRefs", title: "取原生引用", signature: "function getNativeRefs()" },
    ],
  },
  {
    renderType: "YqDictionarySelect",
    name: "字典下拉",
    group: "business",
    category: "select",
    scaffold: { renderType: "YqDictionarySelect", code: "", orgId: "", tenantId: "", isLeaf: true, conditionItems: [], requestParams: {}, defaultProps: { label: "name", value: "value" }, limit: 20, width: "100%", dropdownWidth: "", dropdownHeight: "300px", clearable: false, placeholder: "请选择", searchPlaceholder: "请输入关键字搜索", disabled: false, searchEnable: true, size: "", defaultText: "", modelName: "" },
    props: [
      { name: "code", title: "字典编码", propType: "string", defaultValue: "" },
      { name: "orgId", title: "组织 ID", propType: "string", defaultValue: "" },
      { name: "tenantId", title: "租户 ID", propType: "string", defaultValue: "" },
      { name: "isLeaf", title: "仅叶子节点", propType: "boolean", defaultValue: true },
      { name: "conditionItems", title: "过滤条件", propType: "json", defaultValue: [] },
      { name: "requestParams", title: "附加请求参数", propType: "json", defaultValue: {} },
      { name: "defaultProps", title: "字段映射", propType: "json", defaultValue: { label: "name", value: "value" } },
      { name: "limit", title: "返回条数上限", propType: "number", defaultValue: 20 },
      { name: "width", title: "宽度", propType: "string", defaultValue: "100%" },
      { name: "dropdownWidth", title: "下拉宽度", propType: "string", defaultValue: "" },
      { name: "dropdownHeight", title: "下拉高度", propType: "string", defaultValue: "300px" },
      { name: "clearable", title: "可清空", propType: "boolean", defaultValue: false },
      { name: "placeholder", title: "占位文本", propType: "string", defaultValue: "请选择" },
      { name: "searchPlaceholder", title: "搜索占位", propType: "string", defaultValue: "请输入关键字搜索" },
      { name: "disabled", title: "禁用", propType: "boolean", defaultValue: false },
      { name: "searchEnable", title: "启用搜索", propType: "boolean", defaultValue: true },
      { name: "size", title: "尺寸", propType: SIZE_ENUM, defaultValue: "" },
      { name: "defaultText", title: "默认显示文本", propType: "string", defaultValue: "" },
      modelNameProp(),
    ],
    events: [
      { name: "onMounted", title: "挂载后" },
      { name: "onChange", title: "值变化" },
      { name: "onClear", title: "清空" },
      { name: "onReload", title: "刷新" },
      { name: "onValueRender", title: "值渲染" },
    ],
    methods: reloadClearMethods(),
  },
  {
    renderType: "YqDictionaryTree",
    name: "字典树选择",
    group: "business",
    category: "select",
    scaffold: { renderType: "YqDictionaryTree", code: "", loadMode: "lazy", rootNode: null, moreEnable: true, currentSize: 20, allLimit: 1000, width: "100%", size: "default", reloadEnable: true, orgId: "", tenantId: "", isLeaf: false, defaultProps: { label: "name", value: "value" }, placeholder: "请选择", searchEnable: true, clearable: false, defaultText: "", modelName: "" },
    props: [
      { name: "code", title: "字典编码", propType: "string", defaultValue: "" },
      {
        name: "loadMode",
        title: "加载模式",
        propType: { type: "oneOf", value: ["lazy", "all"], labels: ["懒加载", "全量"] },
        defaultValue: "lazy",
      },
      { name: "rootNode", title: "根节点", propType: "json", defaultValue: null },
      { name: "moreEnable", title: "分页加载更多", propType: "boolean", defaultValue: true },
      { name: "currentSize", title: "分页条数", propType: "number", defaultValue: 20 },
      { name: "allLimit", title: "全量上限", propType: "number", defaultValue: 1000 },
      { name: "width", title: "宽度", propType: "string", defaultValue: "100%" },
      { name: "size", title: "尺寸", propType: SIZE_ENUM, defaultValue: "default" },
      { name: "reloadEnable", title: "显示刷新", propType: "boolean", defaultValue: true },
      { name: "orgId", title: "组织 ID", propType: "string", defaultValue: "" },
      { name: "tenantId", title: "租户 ID", propType: "string", defaultValue: "" },
      { name: "isLeaf", title: "仅叶子节点", propType: "boolean", defaultValue: false },
      { name: "defaultProps", title: "字段映射", propType: "json", defaultValue: { label: "name", value: "value" } },
      { name: "placeholder", title: "占位文本", propType: "string", defaultValue: "请选择" },
      { name: "searchEnable", title: "启用搜索", propType: "boolean", defaultValue: true },
      { name: "clearable", title: "可清空", propType: "boolean", defaultValue: false },
      { name: "defaultText", title: "默认显示文本", propType: "string", defaultValue: "" },
      modelNameProp(),
    ],
    events: [
      { name: "onMounted", title: "挂载后" },
      { name: "onChange", title: "值变化" },
      { name: "onClear", title: "清空" },
      { name: "onReload", title: "刷新" },
      { name: "onValueRender", title: "值渲染" },
    ],
    methods: reloadClearMethods(),
  },
  {
    renderType: "YqOrganizationTreePanel",
    name: "组织树面板",
    group: "business",
    category: "other",
    scaffold: { renderType: "YqOrganizationTreePanel", defaultText: "", multiple: false, placeholder: "请选择", searchPlaceholder: "请输入关键字搜索", defaultProps: { label: "name", value: "id", children: "children" }, moreEnable: true, currentSize: 20, rootNode: null, defaultExpandedKeys: [], searchEnable: true, clearable: false, reloadEnable: true, expandFirst: true, defaultExpandLastNode: true },
    props: [
      { name: "defaultText", title: "默认显示文本", propType: "string", defaultValue: "" },
      { name: "multiple", title: "多选", propType: "boolean", defaultValue: false },
      { name: "placeholder", title: "占位文本", propType: "string", defaultValue: "请选择" },
      { name: "searchPlaceholder", title: "搜索占位", propType: "string", defaultValue: "请输入关键字搜索" },
      { name: "defaultProps", title: "字段映射", propType: "json", defaultValue: { label: "name", value: "id", children: "children" } },
      { name: "moreEnable", title: "分页加载更多", propType: "boolean", defaultValue: true },
      { name: "currentSize", title: "分页条数", propType: "number", defaultValue: 20 },
      { name: "rootNode", title: "根节点", propType: "json", defaultValue: null },
      { name: "defaultExpandedKeys", title: "默认展开键", propType: "json", defaultValue: [] },
      { name: "searchEnable", title: "启用搜索", propType: "boolean", defaultValue: true },
      { name: "clearable", title: "可清空", propType: "boolean", defaultValue: false },
      { name: "reloadEnable", title: "显示刷新", propType: "boolean", defaultValue: true },
      { name: "expandFirst", title: "展开首个节点", propType: "boolean", defaultValue: true },
      { name: "defaultExpandLastNode", title: "展开末级节点", propType: "boolean", defaultValue: true },
    ],
    events: [
      { name: "onMounted", title: "挂载后" },
      { name: "onChange", title: "值变化" },
      { name: "onCheckedChange", title: "勾选变化" },
      { name: "onClear", title: "清空" },
      { name: "onReload", title: "刷新" },
      { name: "onValueRender", title: "值渲染" },
    ],
    methods: [
      { name: "reload", title: "重新加载", signature: "function reload()" },
      { name: "clear", title: "清空", signature: "function clear()" },
      { name: "setChecked", title: "设置勾选节点", signature: "function setChecked(nodes)" },
    ],
  },
  {
    renderType: "YqOrganizationTreeSelect",
    name: "组织树选择",
    group: "business",
    category: "select",
    scaffold: { renderType: "YqOrganizationTreeSelect", defaultText: "", placeholder: "请选择", searchPlaceholder: "请输入关键字搜索", defaultProps: { label: "name", value: "id", children: "children" }, moreEnable: true, currentSize: 20, width: "100%", size: "", dropdownWidth: "", dropdownHeight: "300px", rootNode: null, defaultExpandedKeys: [], searchEnable: true, clearable: false, reloadEnable: true, disabled: false, expandFirst: true, defaultExpandLastNode: true, modelName: "" },
    props: [
      { name: "defaultText", title: "默认显示文本", propType: "string", defaultValue: "" },
      { name: "placeholder", title: "占位文本", propType: "string", defaultValue: "请选择" },
      { name: "searchPlaceholder", title: "搜索占位", propType: "string", defaultValue: "请输入关键字搜索" },
      { name: "defaultProps", title: "字段映射", propType: "json", defaultValue: { label: "name", value: "id", children: "children" } },
      { name: "moreEnable", title: "分页加载更多", propType: "boolean", defaultValue: true },
      { name: "currentSize", title: "分页条数", propType: "number", defaultValue: 20 },
      { name: "width", title: "宽度", propType: "string", defaultValue: "100%" },
      { name: "size", title: "尺寸", propType: SIZE_ENUM, defaultValue: "" },
      { name: "dropdownWidth", title: "下拉宽度", propType: "string", defaultValue: "" },
      { name: "dropdownHeight", title: "下拉高度", propType: "string", defaultValue: "300px" },
      { name: "rootNode", title: "根节点", propType: "json", defaultValue: null },
      { name: "defaultExpandedKeys", title: "默认展开键", propType: "json", defaultValue: [] },
      { name: "searchEnable", title: "启用搜索", propType: "boolean", defaultValue: true },
      { name: "clearable", title: "可清空", propType: "boolean", defaultValue: false },
      { name: "reloadEnable", title: "显示刷新", propType: "boolean", defaultValue: true },
      { name: "disabled", title: "禁用", propType: "boolean", defaultValue: false },
      { name: "expandFirst", title: "展开首个节点", propType: "boolean", defaultValue: true },
      { name: "defaultExpandLastNode", title: "展开末级节点", propType: "boolean", defaultValue: true },
      modelNameProp(),
    ],
    events: [
      { name: "onMounted", title: "挂载后" },
      { name: "onChange", title: "值变化" },
      { name: "onClear", title: "清空" },
      { name: "onReload", title: "刷新" },
      { name: "onValueRender", title: "值渲染" },
    ],
    methods: [
      { name: "reload", title: "重新加载", signature: "function reload()" },
      { name: "clear", title: "清空", signature: "function clear()" },
    ],
  },
  {
    renderType: "YqSelectComMaterial",
    name: "物资选择",
    group: "business",
    category: "select",
    scaffold: { renderType: "YqSelectComMaterial", loadParams: {} },
    props: [
      { name: "loadParams", title: "加载参数", propType: "json", defaultValue: {} },
    ],
    events: [
      { name: "onMounted", title: "挂载后" },
      { name: "onVisibleChange", title: "弹层显隐" },
      { name: "onClose", title: "关闭" },
      { name: "onSelectionChange", title: "选择变化" },
      { name: "onValueRender", title: "值渲染" },
    ],
  },
  {
    renderType: "YqFileSimpleUpload",
    name: "简单文件上传",
    group: "business",
    category: "input",
    scaffold: { renderType: "YqFileSimpleUpload", accept: "", maxSize: 10485760, disabled: false, showConfirmOnDelete: false, buttonText: "点击上传", description: "", action: "#", fileClientOpts: {}, fileObjectOpts: {}, modelName: "" },
    props: [
      { name: "accept", title: "接受文件类型", propType: "string", defaultValue: "" },
      { name: "maxSize", title: "单文件大小上限(MB)", propType: "number", defaultValue: 10485760 },
      { name: "disabled", title: "禁用", propType: "boolean", defaultValue: false },
      { name: "showConfirmOnDelete", title: "删除前确认", propType: "boolean", defaultValue: false },
      { name: "buttonText", title: "按钮文字", propType: "string", defaultValue: "点击上传" },
      { name: "description", title: "说明文字", propType: "string", defaultValue: "" },
      { name: "action", title: "上传地址", propType: "string", defaultValue: "#" },
      { name: "fileClientOpts", title: "文件客户端配置", propType: "json", defaultValue: {} },
      { name: "fileObjectOpts", title: "文件对象配置", propType: "json", defaultValue: {} },
      modelNameProp(),
    ],
    events: [
      { name: "onMounted", title: "挂载后" },
      { name: "onSuccess", title: "上传成功" },
      { name: "onError", title: "上传失败" },
      { name: "onDelete", title: "删除文件" },
      { name: "onValueRender", title: "值渲染" },
    ],
  },
  {
    renderType: "YqFileTableUpload",
    name: "表格文件上传",
    group: "business",
    category: "input",
    scaffold: { renderType: "YqFileTableUpload", maxBatchCount: 10, maxCount: 999, maxSize: 10485760, accept: "", disabled: false, showConfirmOnDelete: false, description: "", action: "", fileClientOpts: {}, fileObjectOpts: {} },
    props: [
      { name: "maxBatchCount", title: "单批数量上限", propType: "number", defaultValue: 10 },
      { name: "maxCount", title: "总数量上限", propType: "number", defaultValue: 999 },
      { name: "maxSize", title: "单文件大小上限(MB)", propType: "number", defaultValue: 10485760 },
      { name: "accept", title: "接受文件类型", propType: "string", defaultValue: "" },
      { name: "disabled", title: "禁用", propType: "boolean", defaultValue: false },
      { name: "showConfirmOnDelete", title: "删除前确认", propType: "boolean", defaultValue: false },
      { name: "description", title: "说明文字", propType: "string", defaultValue: "" },
      { name: "action", title: "上传地址", propType: "string", defaultValue: "" },
      { name: "fileClientOpts", title: "文件客户端配置", propType: "json", defaultValue: {} },
      { name: "fileObjectOpts", title: "文件对象配置", propType: "json", defaultValue: {} },
    ],
    events: [
      { name: "onMounted", title: "挂载后" },
      { name: "onSuccess", title: "上传成功" },
      { name: "onError", title: "上传失败" },
      { name: "onDelete", title: "删除文件" },
      { name: "onRetry", title: "重试" },
      { name: "onDownload", title: "下载" },
      { name: "onValueRender", title: "值渲染" },
    ],
  },
  {
    renderType: "YqFileImageCardUpload",
    name: "图片卡片上传",
    group: "business",
    category: "input",
    scaffold: { renderType: "YqFileImageCardUpload", maxCount: 8, maxBatchCount: 8, maxSize: 20971520, accept: ".png,.jpg,.jpeg", selectable: false, selected: null, disabled: false, showConfirmOnDelete: false, description: "", action: "", fileClientOpts: {}, fileObjectOpts: {} },
    props: [
      { name: "maxCount", title: "图片数量上限", propType: "number", defaultValue: 8 },
      { name: "maxBatchCount", title: "单批数量上限", propType: "number", defaultValue: 8 },
      { name: "maxSize", title: "单文件大小上限(MB)", propType: "number", defaultValue: 20971520 },
      { name: "accept", title: "接受文件类型", propType: "string", defaultValue: ".png,.jpg,.jpeg" },
      { name: "selectable", title: "可选中", propType: "boolean", defaultValue: false },
      { name: "selected", title: "选中项", propType: "json", defaultValue: null },
      { name: "disabled", title: "禁用", propType: "boolean", defaultValue: false },
      { name: "showConfirmOnDelete", title: "删除前确认", propType: "boolean", defaultValue: false },
      { name: "description", title: "说明文字", propType: "string", defaultValue: "" },
      { name: "action", title: "上传地址", propType: "string", defaultValue: "" },
      { name: "fileClientOpts", title: "文件客户端配置", propType: "json", defaultValue: {} },
      { name: "fileObjectOpts", title: "文件对象配置", propType: "json", defaultValue: {} },
    ],
    events: [
      { name: "onMounted", title: "挂载后" },
      { name: "onSuccess", title: "上传成功" },
      { name: "onError", title: "上传失败" },
      { name: "onDelete", title: "删除文件" },
      { name: "onPreview", title: "预览" },
      { name: "onDownload", title: "下载" },
      { name: "onFileSelect", title: "选中图片" },
      { name: "onValueRender", title: "值渲染" },
    ],
  },
  {
    renderType: "YqImageCardPreview",
    name: "图片卡片预览",
    group: "business",
    category: "display",
    scaffold: { renderType: "YqImageCardPreview", imageList: [], cardWidth: "160px", cardHeight: "160px", cardGap: "12px", borderRadius: "6px", previewDisabled: false, downloadDisabled: false, fileClientOpts: {} },
    props: [
      { name: "imageList", title: "图片列表", propType: "json", defaultValue: [] },
      { name: "cardWidth", title: "卡片宽度", propType: "string", defaultValue: "160px" },
      { name: "cardHeight", title: "卡片高度", propType: "string", defaultValue: "160px" },
      { name: "cardGap", title: "卡片间距", propType: "string", defaultValue: "12px" },
      { name: "borderRadius", title: "圆角", propType: "string", defaultValue: "6px" },
      { name: "previewDisabled", title: "禁用预览", propType: "boolean", defaultValue: false },
      { name: "downloadDisabled", title: "禁用下载", propType: "boolean", defaultValue: false },
      { name: "fileClientOpts", title: "文件客户端配置", propType: "json", defaultValue: {} },
    ],
    events: [
      { name: "onMounted", title: "挂载后" },
      { name: "onCardPreview", title: "卡片预览" },
      { name: "onCardDownload", title: "卡片下载" },
      { name: "onCardError", title: "卡片加载失败" },
      { name: "onValueRender", title: "值渲染" },
    ],
  },
];
