import type { ComponentCatalogItem } from "../../../scenario/types";
import { baseEvents, modelNameProp, SIZE_ENUM } from "./shared";

/**
 * 其他块级元素（源码：element-container/block-element/ 除表格/列表外 + column-element/）
 * - Form 表单 / Step 步骤条 / Chart 图表 / YqSearchTreePanel 搜索树面板 / ListElement 列元素
 */
export const elementBlockComponents: ComponentCatalogItem[] = [
  {
    renderType: "Form",
    name: "表单",
    group: "form",
    category: "other",
    scaffold: { renderType: "Form", labelWidth: "100px", size: "", disabled: false, statusIcon: false, inlineMessage: false, labelPosition: "right", showMessage: true, validateOnRuleChange: true, requestFn: "", modelName: "", defaultSlot: null },
    props: [
      { name: "labelWidth", title: "标签宽度", propType: "string", defaultValue: "100px" },
      { name: "size", title: "尺寸", propType: SIZE_ENUM, defaultValue: "" },
      { name: "disabled", title: "禁用", propType: "boolean", defaultValue: false },
      { name: "statusIcon", title: "校验图标", propType: "boolean", defaultValue: false },
      { name: "inlineMessage", title: "行内校验信息", propType: "boolean", defaultValue: false },
      {
        name: "labelPosition",
        title: "标签位置",
        propType: { type: "oneOf", value: ["left", "right", "top"], labels: ["左", "右", "上"] },
        defaultValue: "right",
      },
      { name: "showMessage", title: "显示校验信息", propType: "boolean", defaultValue: true },
      { name: "validateOnRuleChange", title: "规则变化即校验", propType: "boolean", defaultValue: true },
      { name: "rules", title: "校验规则", propType: "json", defaultValue: undefined },
      { name: "requestFn", title: "保存请求函数", propType: "string", defaultValue: "", setter: "RequestFnSetter" },
      modelNameProp(),
    ],
    events: baseEvents(),
    // 数组槽（assem-form.vue v-for 消费）
    slots: [{ name: "defaultSlot", slotType: "array", description: "表单内容" }],
    methods: [
      { name: "validateForm", title: "触发表单校验", signature: "function validateForm()" },
      { name: "resetFields", title: "重置表单", signature: "function resetFields()" },
      { name: "clearValidate", title: "清除校验", signature: "function clearValidate(props)" },
      { name: "saveFormData", title: "保存表单数据", signature: "function saveFormData(requestFn)" },
    ],
  },
  {
    renderType: "Step",
    name: "步骤条",
    group: "data",
    category: "other",
    scaffold: { renderType: "Step", active: 0, space: "", alignCenter: false, simple: false, processStatus: "process", finishStatus: "finish", stepItem: [{ title: "步骤一", description: "" }] },
    props: [
      { name: "active", title: "当前步骤", propType: "number", defaultValue: 0 },
      { name: "space", title: "间距", propType: "string", defaultValue: "" },
      { name: "alignCenter", title: "居中对齐", propType: "boolean", defaultValue: false },
      { name: "simple", title: "简洁风格", propType: "boolean", defaultValue: false },
      {
        name: "processStatus",
        title: "当前步骤状态",
        propType: { type: "oneOf", value: ["wait", "process", "finish", "error", "success"], labels: ["等待", "进行中", "完成", "错误", "成功"] },
        defaultValue: "process",
      },
      {
        name: "finishStatus",
        title: "完成步骤状态",
        propType: { type: "oneOf", value: ["wait", "process", "finish", "error", "success"], labels: ["等待", "进行中", "完成", "错误", "成功"] },
        defaultValue: "finish",
      },
      { name: "stepItem", title: "步骤项配置", propType: "json", defaultValue: [] },
    ],
    events: [
      { name: "onMounted", title: "挂载后" },
      { name: "onChange", title: "步骤变化" },
      { name: "onValueRender", title: "值渲染" },
    ],
  },
  {
    renderType: "Chart",
    name: "G2Plot 图表",
    group: "data",
    category: "other",
    scaffold: { renderType: "Chart", g2PlotName: "Line", width: "100%", height: "300px", loading: false, skeletonRows: 3, options: {} },
    props: [
      { name: "g2PlotName", title: "图表类型", propType: "string", defaultValue: "Line" },
      { name: "width", title: "宽度", propType: "string", defaultValue: "100%" },
      { name: "height", title: "高度", propType: "string", defaultValue: "300px" },
      { name: "loading", title: "加载中", propType: "boolean", defaultValue: false },
      { name: "skeletonRows", title: "骨架屏行数", propType: "number", defaultValue: 3 },
      { name: "options", title: "G2Plot 配置", propType: "json", defaultValue: {} },
    ],
    events: [
      { name: "onMounted", title: "挂载后" },
      { name: "onClick", title: "点击" },
      { name: "onElementClick", title: "图形元素点击" },
      { name: "onLegendClick", title: "图例点击" },
    ],
    methods: [
      { name: "loadData", title: "加载数据", signature: "function loadData(data)" },
      { name: "updateOption", title: "更新配置", signature: "function updateOption(option)" },
      { name: "reRender", title: "重新渲染", signature: "function reRender()" },
    ],
  },
  {
    renderType: "YqSearchTreePanel",
    name: "搜索树面板",
    group: "data",
    category: "other",
    scaffold: { renderType: "YqSearchTreePanel", defaultText: "", placeholder: "请选择", searchPlaceholder: "输入关键词搜索", width: "", size: "", dropdownWidth: "", dropdownHeight: "", rootNode: null, defaultExpandedKeys: [], moreEnable: false, currentSize: 20, disabled: false, searchEnable: true, clearable: true, reloadEnable: false, expandFirst: false, defaultExpandLastNode: false, requestFn: "", defaultProps: { label: "label", value: "value" } },
    props: [
      { name: "defaultText", title: "默认显示文本", propType: "string", defaultValue: "" },
      { name: "placeholder", title: "占位文本", propType: "string", defaultValue: "请选择" },
      { name: "searchPlaceholder", title: "搜索占位", propType: "string", defaultValue: "输入关键词搜索" },
      { name: "width", title: "宽度", propType: "string", defaultValue: "" },
      { name: "size", title: "尺寸", propType: SIZE_ENUM, defaultValue: "" },
      { name: "dropdownWidth", title: "下拉宽度", propType: "string", defaultValue: "" },
      { name: "dropdownHeight", title: "下拉高度", propType: "string", defaultValue: "" },
      { name: "rootNode", title: "根节点", propType: "json", defaultValue: null },
      { name: "defaultExpandedKeys", title: "默认展开键", propType: "json", defaultValue: [] },
      { name: "moreEnable", title: "分页加载更多", propType: "boolean", defaultValue: false },
      { name: "currentSize", title: "分页条数", propType: "number", defaultValue: 20 },
      { name: "disabled", title: "禁用", propType: "boolean", defaultValue: false },
      { name: "searchEnable", title: "启用搜索", propType: "boolean", defaultValue: true },
      { name: "clearable", title: "可清空", propType: "boolean", defaultValue: true },
      { name: "reloadEnable", title: "显示刷新", propType: "boolean", defaultValue: false },
      { name: "expandFirst", title: "展开首个节点", propType: "boolean", defaultValue: false },
      { name: "defaultExpandLastNode", title: "展开末级节点", propType: "boolean", defaultValue: false },
      { name: "requestFn", title: "请求函数", propType: "string", defaultValue: "", setter: "RequestFnSetter" },
      { name: "defaultProps", title: "字段映射", propType: "json", defaultValue: { label: "label", value: "value" } },
    ],
    events: [
      { name: "onMounted", title: "挂载后" },
      { name: "onSelectChange", title: "选中变化" },
      { name: "onLoadData", title: "节点加载" },
      { name: "onLoadSearchData", title: "搜索数据加载" },
      { name: "onClear", title: "清空" },
      { name: "onReload", title: "刷新" },
      { name: "onValueTreeRender", title: "树值渲染" },
      { name: "onValueListRender", title: "列表值渲染" },
    ],
    methods: [{ name: "reload", title: "重新加载", signature: "function reload()" }],
  },
  {
    renderType: "ListElement",
    name: "列元素",
    group: "data",
    category: "other",
    scaffold: { renderType: "ListElement", defaultSlot: null },
    props: [],
    events: baseEvents(),
  },
];
