import type { ComponentCatalogItem } from "../../../scenario/types";
import { baseEvents, modelNameProp, SIZE_ENUM } from "./shared";

/**
 * 行内显示组件（源码：components/element-container/line-element/display-element/ + business-component/assem-yq-advanced-filter.vue）
 */
export const lineDisplayComponents: ComponentCatalogItem[] = [
  {
    renderType: "Button",
    name: "按钮",
    group: "basic",
    category: "button",
    scaffold: { renderType: "Button", content: "按钮", type: "primary", size: "", plain: true, text: false, round: false, circle: false, disabled: false, loading: false, link: false, icon: "", iconFont: "" },
    props: [
      { name: "content", title: "按钮文字", propType: "string", defaultValue: "按钮" },
      {
        name: "type",
        title: "类型",
        propType: { type: "oneOf", value: ["", "primary", "success", "warning", "info", "danger", "text"], labels: ["默认", "主要", "成功", "警告", "信息", "危险", "文字"] },
        defaultValue: "primary",
      },
      { name: "size", title: "尺寸", propType: SIZE_ENUM, defaultValue: "" },
      { name: "plain", title: "朴素", propType: "boolean", defaultValue: false },
      { name: "text", title: "文字按钮", propType: "boolean", defaultValue: false },
      { name: "link", title: "链接按钮", propType: "boolean", defaultValue: false },
      { name: "round", title: "圆角", propType: "boolean", defaultValue: false },
      { name: "circle", title: "圆形", propType: "boolean", defaultValue: false },
      { name: "disabled", title: "禁用", propType: "boolean", defaultValue: false },
      { name: "loading", title: "加载中", propType: "boolean", defaultValue: false },
      { name: "icon", title: "图标", propType: "icon", defaultValue: "", setter: "IconSetter" },
      { name: "iconFont", title: "iconfont 图标类名", propType: "string", defaultValue: "" },
      modelNameProp(),
    ],
    events: [
      { name: "onMounted", title: "挂载后" },
      { name: "onClick", title: "点击" },
      { name: "onValueRender", title: "值渲染" },
    ],
  },
  {
    renderType: "YqLabel",
    name: "标签文本",
    group: "basic",
    category: "display",
    scaffold: { renderType: "YqLabel", content: "标签文字", placeholder: "", modelName: "" },
    props: [
      { name: "content", title: "文本", propType: "string", defaultValue: "标签文字" },
      { name: "placeholder", title: "占位文本", propType: "string", defaultValue: "" },
      modelNameProp(),
    ],
    events: [
      { name: "onMounted", title: "挂载后" },
      { name: "onClick", title: "点击" },
      { name: "onValueRender", title: "值渲染" },
    ],
  },
  {
    renderType: "Tag",
    name: "标记",
    group: "basic",
    category: "display",
    scaffold: { renderType: "Tag", content: "标记", type: "primary", closable: false, hit: false, round: false, effect: "light", size: "" },
    props: [
      { name: "content", title: "内容", propType: "string", defaultValue: "标记" },
      {
        name: "type",
        title: "类型",
        propType: { type: "oneOf", value: ["primary", "success", "info", "warning", "danger"], labels: ["主要", "成功", "信息", "警告", "危险"] },
        defaultValue: "primary",
      },
      { name: "closable", title: "可关闭", propType: "boolean", defaultValue: false },
      { name: "hit", title: "描边", propType: "boolean", defaultValue: false },
      { name: "round", title: "圆角", propType: "boolean", defaultValue: false },
      {
        name: "effect",
        title: "主题",
        propType: { type: "oneOf", value: ["dark", "light", "plain"], labels: ["深色", "浅色", "朴素"] },
        defaultValue: "light",
      },
      { name: "size", title: "尺寸", propType: SIZE_ENUM, defaultValue: "" },
      modelNameProp(),
    ],
    events: [
      { name: "onMounted", title: "挂载后" },
      { name: "onClick", title: "点击" },
      { name: "onClose", title: "关闭" },
      { name: "onValueRender", title: "值渲染" },
    ],
  },
  {
    renderType: "FilterSummary",
    name: "筛选摘要",
    group: "basic",
    category: "display",
    scaffold: { renderType: "FilterSummary", filterItems: [], width: "" },
    props: [
      { name: "filterItems", title: "筛选项摘要", propType: "json", defaultValue: [] },
      { name: "width", title: "宽度", propType: "string", defaultValue: "" },
    ],
    events: baseEvents(),
  },
  {
    renderType: "Image",
    name: "图片",
    group: "basic",
    category: "display",
    scaffold: { renderType: "Image", content: "", zoomRate: 1, preview: false, initialIndex: 0, hideOnClickModal: false, loading: "eager", srcList: [], fit: "" },
    props: [
      { name: "content", title: "图片地址", propType: "string", defaultValue: "" },
      modelNameProp(),
      { name: "zoomRate", title: "缩放倍率", propType: "number", defaultValue: 1 },
      { name: "preview", title: "允许预览", propType: "boolean", defaultValue: false },
      { name: "initialIndex", title: "预览起始索引", propType: "number", defaultValue: 0 },
      { name: "hideOnClickModal", title: "点击遮罩关闭预览", propType: "boolean", defaultValue: false },
      {
        name: "loading",
        title: "加载方式",
        propType: { type: "oneOf", value: ["eager", "lazy"], labels: ["立即", "懒加载"] },
        defaultValue: "eager",
      },
      { name: "srcList", title: "预览图列表", propType: "json", defaultValue: [] },
      {
        name: "fit",
        title: "填充模式",
        propType: { type: "oneOf", value: ["", "fill", "contain", "cover", "none", "scale-down"], labels: ["默认", "拉伸", "包含", "覆盖", "无", "缩小"] },
        defaultValue: "",
      },
    ],
    events: [
      { name: "onMounted", title: "挂载后" },
      { name: "onClose", title: "预览关闭" },
      { name: "onShow", title: "预览打开" },
      { name: "onValueRender", title: "值渲染" },
    ],
  },
  {
    renderType: "Icon",
    name: "图标",
    group: "basic",
    category: "display",
    scaffold: { renderType: "Icon", iconName: "", iconFont: "", size: "21", color: "#2468f2", wrapSize: 40, wrapBg: "" },
    props: [
      { name: "iconName", title: "图标名", propType: "icon", defaultValue: "", setter: "IconSetter" },
      { name: "iconFont", title: "iconfont 类名", propType: "string", defaultValue: "" },
      { name: "size", title: "图标尺寸", propType: "string", defaultValue: "21" },
      { name: "color", title: "颜色", propType: "color", defaultValue: "#2468f2", setter: "ColorSetter" },
      { name: "wrapSize", title: "容器尺寸", propType: "number", defaultValue: 40 },
      { name: "wrapBg", title: "容器背景色", propType: "color", defaultValue: "", setter: "ColorSetter" },
    ],
    events: [
      { name: "onMounted", title: "挂载后" },
      { name: "onClick", title: "点击" },
      { name: "onValueRender", title: "值渲染" },
    ],
  },
  {
    renderType: "RawHtml",
    name: "富文本 HTML",
    group: "basic",
    category: "display",
    scaffold: { renderType: "RawHtml", content: "", modelName: "" },
    props: [
      { name: "content", title: "HTML 内容（支持 {{model}} 插值）", propType: "string", defaultValue: "", setter: "TextareaSetter" },
      modelNameProp(),
    ],
    events: [
      { name: "onMounted", title: "挂载后" },
      { name: "onClick", title: "点击" },
      { name: "onValueRender", title: "值渲染" },
    ],
  },
  {
    renderType: "Dropdown",
    name: "下拉菜单",
    group: "basic",
    category: "display",
    scaffold: { renderType: "Dropdown", content: "更多", type: "primary", plain: false, disabled: false, size: "", placement: "bottom", dropdownItem: [] },
    props: [
      { name: "content", title: "触发文字", propType: "string", defaultValue: "更多" },
      {
        name: "type",
        title: "类型",
        propType: { type: "oneOf", value: ["", "primary", "success", "warning", "info", "danger"], labels: ["默认", "主要", "成功", "警告", "信息", "危险"] },
        defaultValue: "primary",
      },
      { name: "plain", title: "朴素", propType: "boolean", defaultValue: false },
      { name: "disabled", title: "禁用", propType: "boolean", defaultValue: false },
      { name: "size", title: "尺寸", propType: SIZE_ENUM, defaultValue: "" },
      {
        name: "placement",
        title: "弹出位置",
        propType: { type: "oneOf", value: ["top", "top-start", "top-end", "bottom", "bottom-start", "bottom-end"], labels: ["上", "左上", "右上", "下", "左下", "右下"] },
        defaultValue: "bottom",
      },
      { name: "dropdownItem", title: "菜单项配置", propType: "json", defaultValue: [] },
    ],
    events: [
      { name: "onMounted", title: "挂载后" },
      { name: "onCommand", title: "菜单项点击" },
      { name: "onValueRender", title: "值渲染" },
    ],
  },
  {
    renderType: "YqAdvancedFilter",
    name: "高级筛选器",
    group: "basic",
    category: "display",
    scaffold: { renderType: "YqAdvancedFilter", filterCode: "", fieldList: [], presetSchemes: [] },
    props: [
      { name: "filterCode", title: "过滤器编码（服务端持久化键）", propType: "string", defaultValue: "" },
      { name: "fieldList", title: "筛选字段列表", propType: "json", defaultValue: [] },
      { name: "presetSchemes", title: "预置方案", propType: "json", defaultValue: [] },
    ],
    events: [
      { name: "onMounted", title: "挂载后" },
      { name: "onSearch", title: "查询" },
      { name: "onValueRender", title: "值渲染" },
    ],
    methods: [
      { name: "clearFilterState", title: "清空筛选", signature: "function clearFilterState(shouldEmitSearch)" },
    ],
  },
  {
    renderType: "UiSkeletonBlockSlot",
    name: "区块占位（内部）",
    group: "basic",
    category: "display",
    scaffold: { renderType: "UiSkeletonBlockSlot", blockId: "", blockRule: "", blockSourceRenderType: "" },
    props: [
      { name: "blockId", title: "区块 ID", propType: "string", defaultValue: "" },
      { name: "blockRule", title: "区块规则", propType: "string", defaultValue: "" },
      { name: "blockSourceRenderType", title: "来源组件类型", propType: "string", defaultValue: "" },
    ],
    events: baseEvents(),
  },
];
