import type { ComponentCatalogItem } from "../../../scenario/types";
import {
  inputEvents,
  modelNameProp,
  optionsMethods,
  remoteOptionsProps,
  SIZE_ENUM,
} from "./shared";

/**
 * 行内输入组件（源码：components/element-container/line-element/input-element/ + block-element 表单项）
 */
export const lineInputComponents: ComponentCatalogItem[] = [
  {
    renderType: "Input",
    name: "输入框",
    group: "form",
    category: "input",
    scaffold: { renderType: "Input", type: "text", placeholder: "请输入", maxlength: "", minlength: 0, clearable: true, disabled: false, readonly: false, size: "", rows: 2, modelName: "" },
    props: [
      {
        name: "type",
        title: "类型",
        propType: { type: "oneOf", value: ["text", "textarea", "password"], labels: ["文本", "多行文本", "密码"] },
        defaultValue: "text",
      },
      { name: "placeholder", title: "占位文本", propType: "string", defaultValue: "请输入" },
      { name: "maxlength", title: "最大长度", propType: "number", defaultValue: "" },
      { name: "minlength", title: "最小长度", propType: "number", defaultValue: 0 },
      { name: "clearable", title: "可清空", propType: "boolean", defaultValue: true },
      { name: "disabled", title: "禁用", propType: "boolean", defaultValue: false },
      { name: "readonly", title: "只读", propType: "boolean", defaultValue: false },
      { name: "size", title: "尺寸", propType: SIZE_ENUM, defaultValue: "" },
      { name: "rows", title: "行数(textarea)", propType: "number", defaultValue: 2 },
      modelNameProp(),
    ],
    events: inputEvents(true),
  },
  {
    renderType: "InputNumber",
    name: "数字输入",
    group: "form",
    category: "input",
    scaffold: { renderType: "InputNumber", min: undefined, max: undefined, step: 1, stepStrictly: false, precision: undefined, size: "", readonly: false, disabled: false, controls: true, placeholder: "请输入", modelName: "" },
    props: [
      { name: "min", title: "最小值", propType: "number", defaultValue: undefined },
      { name: "max", title: "最大值", propType: "number", defaultValue: undefined },
      { name: "step", title: "步长", propType: "number", defaultValue: 1 },
      { name: "stepStrictly", title: "严格步进", propType: "boolean", defaultValue: false },
      { name: "precision", title: "精度", propType: "number", defaultValue: undefined },
      { name: "size", title: "尺寸", propType: SIZE_ENUM, defaultValue: "" },
      { name: "readonly", title: "只读", propType: "boolean", defaultValue: false },
      { name: "disabled", title: "禁用", propType: "boolean", defaultValue: false },
      { name: "controls", title: "控制按钮", propType: "boolean", defaultValue: true },
      { name: "placeholder", title: "占位文本", propType: "string", defaultValue: "请输入" },
      modelNameProp(),
    ],
    events: inputEvents(true),
  },
  {
    renderType: "Switch",
    name: "开关",
    group: "form",
    category: "input",
    scaffold: { renderType: "Switch", disabled: false, loading: false, size: "", inlinePrompt: false, activeIcon: "", inactiveIcon: "", activeText: "", inactiveText: "", activeValue: true, inactiveValue: false, modelName: "" },
    props: [
      { name: "disabled", title: "禁用", propType: "boolean", defaultValue: false },
      { name: "loading", title: "加载中", propType: "boolean", defaultValue: false },
      { name: "size", title: "尺寸", propType: SIZE_ENUM, defaultValue: "" },
      { name: "inlinePrompt", title: "文字显于内", propType: "boolean", defaultValue: false },
      { name: "activeIcon", title: "打开图标", propType: "icon", defaultValue: "", setter: "IconSetter" },
      { name: "inactiveIcon", title: "关闭图标", propType: "icon", defaultValue: "", setter: "IconSetter" },
      { name: "activeText", title: "打开文字", propType: "string", defaultValue: "" },
      { name: "inactiveText", title: "关闭文字", propType: "string", defaultValue: "" },
      { name: "activeValue", title: "打开值", propType: "json", defaultValue: true },
      { name: "inactiveValue", title: "关闭值", propType: "json", defaultValue: false },
      modelNameProp(),
    ],
    events: inputEvents(),
  },
  {
    renderType: "Checkbox",
    name: "复选框",
    group: "form",
    category: "input",
    scaffold: { renderType: "Checkbox", label: "复选框", disabled: false, border: false, size: "", modelName: "" },
    props: [
      { name: "label", title: "标签文字", propType: "string", defaultValue: "复选框" },
      { name: "disabled", title: "禁用", propType: "boolean", defaultValue: false },
      { name: "border", title: "边框", propType: "boolean", defaultValue: false },
      { name: "size", title: "尺寸", propType: SIZE_ENUM, defaultValue: "" },
      modelNameProp(),
    ],
    events: inputEvents(),
  },
  {
    renderType: "CheckboxGroup",
    name: "复选框组",
    group: "form",
    category: "select",
    scaffold: { renderType: "CheckboxGroup", disabled: false, size: "", type: "", border: false, min: undefined, max: undefined, textColor: "", fill: "", modelName: "", itemData: [], requestFn: "", defaultProps: { label: "label", value: "value" } },
    props: [
      { name: "disabled", title: "禁用", propType: "boolean", defaultValue: false },
      { name: "size", title: "尺寸", propType: SIZE_ENUM, defaultValue: "" },
      {
        name: "type",
        title: "按钮样式",
        propType: { type: "oneOf", value: ["", "button"], labels: ["默认", "按钮"] },
        defaultValue: "",
      },
      { name: "border", title: "边框", propType: "boolean", defaultValue: false },
      { name: "min", title: "最少勾选数", propType: "number", defaultValue: undefined },
      { name: "max", title: "最多勾选数", propType: "number", defaultValue: undefined },
      { name: "textColor", title: "激活文字色", propType: "color", defaultValue: "", setter: "ColorSetter" },
      { name: "fill", title: "激活填充色", propType: "color", defaultValue: "", setter: "ColorSetter" },
      modelNameProp(),
      ...remoteOptionsProps(),
    ],
    events: inputEvents(),
    methods: optionsMethods(),
  },
  {
    renderType: "RadioGroup",
    name: "单选组",
    group: "form",
    category: "select",
    scaffold: { renderType: "RadioGroup", disabled: false, size: "", type: "", textColor: "", fill: "", modelName: "", itemData: [], requestFn: "", defaultProps: { label: "label", value: "value" } },
    props: [
      { name: "disabled", title: "禁用", propType: "boolean", defaultValue: false },
      { name: "size", title: "尺寸", propType: SIZE_ENUM, defaultValue: "" },
      {
        name: "type",
        title: "样式",
        propType: { type: "oneOf", value: ["", "button", "border"], labels: ["默认", "按钮", "带边框"] },
        defaultValue: "",
      },
      { name: "textColor", title: "激活文字色", propType: "color", defaultValue: "", setter: "ColorSetter" },
      { name: "fill", title: "激活填充色", propType: "color", defaultValue: "", setter: "ColorSetter" },
      modelNameProp(),
      ...remoteOptionsProps(),
    ],
    events: inputEvents(),
    methods: optionsMethods(),
  },
  {
    renderType: "Select",
    name: "下拉选择",
    group: "form",
    category: "select",
    scaffold: { renderType: "Select", multiple: false, disabled: false, size: "", clearable: true, filterable: false, collapseTags: false, collapseTagsTooltip: false, multipleLimit: 0, placeholder: "请选择", valueKey: "value", optionTemplate: "", modelName: "", itemData: [], requestFn: "", defaultProps: { label: "label", value: "value", subLabel: "", nextLabel: "" } },
    props: [
      { name: "multiple", title: "多选", propType: "boolean", defaultValue: false },
      { name: "disabled", title: "禁用", propType: "boolean", defaultValue: false },
      { name: "size", title: "尺寸", propType: SIZE_ENUM, defaultValue: "" },
      { name: "clearable", title: "可清空", propType: "boolean", defaultValue: true },
      { name: "filterable", title: "可搜索", propType: "boolean", defaultValue: false },
      { name: "collapseTags", title: "折叠标签", propType: "boolean", defaultValue: false },
      { name: "collapseTagsTooltip", title: "折叠提示", propType: "boolean", defaultValue: false },
      { name: "multipleLimit", title: "多选上限", propType: "number", defaultValue: 0 },
      { name: "placeholder", title: "占位文本", propType: "string", defaultValue: "请选择" },
      { name: "valueKey", title: "取值字段", propType: "string", defaultValue: "value" },
      { name: "optionTemplate", title: "选项模板", propType: "string", defaultValue: "" },
      modelNameProp(),
      ...remoteOptionsProps({ label: "label", value: "value" }),
    ],
    events: [
      { name: "onMounted", title: "挂载后" },
      { name: "onChange", title: "值变化" },
      { name: "onVisibleChange", title: "下拉显隐" },
      { name: "onClear", title: "清空" },
      { name: "onLoadData", title: "加载选项数据" },
      { name: "onValueRender", title: "值渲染" },
    ],
    methods: optionsMethods(),
  },
  {
    renderType: "DatePicker",
    name: "日期选择",
    group: "form",
    category: "date",
    scaffold: { renderType: "DatePicker", type: "date", placeholder: "请选择日期", startPlaceholder: "开始日期", endPlaceholder: "结束日期", format: "YYYY-MM-DD", valueFormat: "YYYY-MM-DD", rangeSeparator: "-", readonly: false, disabled: false, editable: true, clearable: true, size: "", unlinkPanels: false, modelName: "" },
    props: [
      {
        name: "type",
        title: "类型",
        propType: { type: "oneOf", value: ["date", "dates", "datetime", "week", "month", "year", "daterange", "monthrange"], labels: ["日期", "多日期", "日期时间", "周", "月", "年", "日期区间", "月份区间"] },
        defaultValue: "date",
      },
      { name: "placeholder", title: "占位文本", propType: "string", defaultValue: "请选择日期" },
      { name: "startPlaceholder", title: "开始占位", propType: "string", defaultValue: "开始日期" },
      { name: "endPlaceholder", title: "结束占位", propType: "string", defaultValue: "结束日期" },
      { name: "format", title: "显示格式", propType: "string", defaultValue: "YYYY-MM-DD" },
      { name: "valueFormat", title: "值格式", propType: "string", defaultValue: "YYYY-MM-DD" },
      { name: "rangeSeparator", title: "分隔符", propType: "string", defaultValue: "-" },
      { name: "defaultValue", title: "默认值", propType: "string", defaultValue: undefined },
      { name: "defaultTime", title: "默认时间", propType: "string", defaultValue: undefined },
      { name: "readonly", title: "只读", propType: "boolean", defaultValue: false },
      { name: "disabled", title: "禁用", propType: "boolean", defaultValue: false },
      { name: "editable", title: "可输入", propType: "boolean", defaultValue: true },
      { name: "clearable", title: "可清空", propType: "boolean", defaultValue: true },
      { name: "size", title: "尺寸", propType: SIZE_ENUM, defaultValue: "" },
      { name: "unlinkPanels", title: "联动面板解除", propType: "boolean", defaultValue: false },
      { name: "shortcuts", title: "快捷选项", propType: "json", defaultValue: undefined },
      modelNameProp(),
    ],
    events: inputEvents(true),
    methods: [
      { name: "focus", title: "聚焦", signature: "function focus()" },
      { name: "handleOpen", title: "打开面板", signature: "function handleOpen()" },
      { name: "handleClose", title: "关闭面板", signature: "function handleClose()" },
    ],
  },
  {
    renderType: "YqDateRangePicker",
    name: "日期区间（云阙）",
    group: "form",
    category: "date",
    scaffold: { renderType: "YqDateRangePicker", type: "daterange", placeholder: "请选择", startPlaceholder: "开始日期", endPlaceholder: "结束日期", valueFormat: "YYYY-MM-DD", size: "", selectBarItems: [], defaultPicked: "", rangeLimit: 0, accountDay: null, readonly: false, disabled: false, clearable: true, modelName: "" },
    props: [
      { name: "type", title: "类型", propType: "string", defaultValue: "daterange" },
      { name: "placeholder", title: "占位文本", propType: "string", defaultValue: "请选择" },
      { name: "startPlaceholder", title: "开始占位", propType: "string", defaultValue: "开始日期" },
      { name: "endPlaceholder", title: "结束占位", propType: "string", defaultValue: "结束日期" },
      { name: "valueFormat", title: "值格式", propType: "string", defaultValue: "YYYY-MM-DD" },
      { name: "size", title: "尺寸", propType: SIZE_ENUM, defaultValue: "" },
      { name: "selectBarItems", title: "快捷选项条目", propType: "json", defaultValue: [] },
      { name: "defaultPicked", title: "默认选中快捷项", propType: "string", defaultValue: "" },
      { name: "rangeLimit", title: "区间天数限制", propType: "number", defaultValue: 0 },
      { name: "accountDay", title: "记账日配置", propType: "json", defaultValue: null },
      { name: "readonly", title: "只读", propType: "boolean", defaultValue: false },
      { name: "disabled", title: "禁用", propType: "boolean", defaultValue: false },
      { name: "clearable", title: "可清空", propType: "boolean", defaultValue: true },
      modelNameProp(),
    ],
    events: inputEvents(),
  },
  {
    renderType: "TimePicker",
    name: "时间选择",
    group: "form",
    category: "date",
    scaffold: { renderType: "TimePicker", placeholder: "请选择时间", isRange: false, arrowControl: false, format: "HH:mm:ss", readonly: false, disabled: false, editable: true, clearable: true, size: "", modelName: "" },
    props: [
      { name: "placeholder", title: "占位文本", propType: "string", defaultValue: "请选择时间" },
      { name: "isRange", title: "区间选择", propType: "boolean", defaultValue: false },
      { name: "arrowControl", title: "箭头操控", propType: "boolean", defaultValue: false },
      { name: "format", title: "格式", propType: "string", defaultValue: "HH:mm:ss" },
      { name: "readonly", title: "只读", propType: "boolean", defaultValue: false },
      { name: "disabled", title: "禁用", propType: "boolean", defaultValue: false },
      { name: "editable", title: "可输入", propType: "boolean", defaultValue: true },
      { name: "clearable", title: "可清空", propType: "boolean", defaultValue: true },
      { name: "size", title: "尺寸", propType: SIZE_ENUM, defaultValue: "" },
      { name: "disabledHours", title: "禁用小时", propType: "string", defaultValue: undefined },
      { name: "disabledMinutes", title: "禁用分钟", propType: "string", defaultValue: undefined },
      { name: "disabledSeconds", title: "禁用秒", propType: "string", defaultValue: undefined },
      modelNameProp(),
    ],
    events: [
      ...inputEvents(true),
      { name: "onVisibleChange", title: "面板显隐" },
    ],
    methods: [
      { name: "getTimePickerInstance", title: "取原生实例", signature: "function getTimePickerInstance()" },
    ],
  },
  {
    renderType: "YqSearchSelect",
    name: "搜索下拉（云阙）",
    group: "form",
    category: "select",
    scaffold: { renderType: "YqSearchSelect", filterName: "", defaultText: "", limit: 20, width: "", size: "", allowCreate: false, disabled: false, clearable: true, searchEnable: true, placeholder: "请选择", searchPlaceholder: "输入关键词搜索", dropdownWidth: "", dropdownHeight: "", modelName: "", requestFn: "", defaultProps: { label: "label", value: "value" } },
    props: [
      { name: "filterName", title: "过滤字段名", propType: "string", defaultValue: "" },
      { name: "defaultText", title: "默认显示文本", propType: "string", defaultValue: "" },
      { name: "limit", title: "返回条数上限", propType: "number", defaultValue: 20 },
      { name: "width", title: "宽度", propType: "string", defaultValue: "" },
      { name: "size", title: "尺寸", propType: SIZE_ENUM, defaultValue: "" },
      { name: "allowCreate", title: "允许创建", propType: "boolean", defaultValue: false },
      { name: "disabled", title: "禁用", propType: "boolean", defaultValue: false },
      { name: "clearable", title: "可清空", propType: "boolean", defaultValue: true },
      { name: "searchEnable", title: "启用搜索", propType: "boolean", defaultValue: true },
      { name: "placeholder", title: "占位文本", propType: "string", defaultValue: "请选择" },
      { name: "searchPlaceholder", title: "搜索占位", propType: "string", defaultValue: "输入关键词搜索" },
      { name: "dropdownWidth", title: "下拉宽度", propType: "string", defaultValue: "" },
      { name: "dropdownHeight", title: "下拉高度", propType: "string", defaultValue: "" },
      { name: "requestFn", title: "请求函数", propType: "string", defaultValue: "", setter: "RequestFnSetter" },
      modelNameProp(),
      { name: "defaultProps", title: "选项字段映射", propType: "json", defaultValue: { label: "label", value: "value" } },
    ],
    events: [
      { name: "onMounted", title: "挂载后" },
      { name: "onChange", title: "值变化" },
      { name: "onClear", title: "清空" },
      { name: "onLoadData", title: "加载数据" },
      { name: "onFilterCurrent", title: "本地过滤" },
      { name: "onCurrentCreate", title: "创建新条目" },
      { name: "onValueRender", title: "值渲染" },
    ],
  },
  {
    renderType: "YqSearchTreeSelect",
    name: "搜索树选择（云阙）",
    group: "form",
    category: "select",
    scaffold: { renderType: "YqSearchTreeSelect", defaultText: "", placeholder: "请选择", searchPlaceholder: "输入关键词搜索", width: "", size: "", dropdownWidth: "", dropdownHeight: "", rootNode: null, defaultExpandedKeys: [], searchEnable: true, clearable: true, reloadEnable: false, disabled: false, expandFirst: false, moreEnable: false, currentSize: 20, requestFn: "", defaultProps: { label: "label", value: "value" } },
    props: [
      { name: "defaultText", title: "默认显示文本", propType: "string", defaultValue: "" },
      { name: "placeholder", title: "占位文本", propType: "string", defaultValue: "请选择" },
      { name: "searchPlaceholder", title: "搜索占位", propType: "string", defaultValue: "输入关键词搜索" },
      { name: "width", title: "宽度", propType: "string", defaultValue: "" },
      { name: "size", title: "尺寸", propType: SIZE_ENUM, defaultValue: "" },
      { name: "dropdownWidth", title: "下拉宽度", propType: "string", defaultValue: "" },
      { name: "dropdownHeight", title: "下拉高度", propType: "string", defaultValue: "" },
      { name: "rootNode", title: "根节点", propType: "json", defaultValue: null },
      { name: "defaultExpandedKeys", title: "默认展开键", propType: "json", defaultValue: [] },
      { name: "searchEnable", title: "启用搜索", propType: "boolean", defaultValue: true },
      { name: "clearable", title: "可清空", propType: "boolean", defaultValue: true },
      { name: "reloadEnable", title: "显示刷新", propType: "boolean", defaultValue: false },
      { name: "disabled", title: "禁用", propType: "boolean", defaultValue: false },
      { name: "expandFirst", title: "展开首个节点", propType: "boolean", defaultValue: false },
      { name: "moreEnable", title: "分页加载更多", propType: "boolean", defaultValue: false },
      { name: "currentSize", title: "分页条数", propType: "number", defaultValue: 20 },
      { name: "requestFn", title: "请求函数", propType: "string", defaultValue: "", setter: "RequestFnSetter" },
      { name: "defaultProps", title: "字段映射", propType: "json", defaultValue: { label: "label", value: "value" } },
    ],
    events: [
      { name: "onMounted", title: "挂载后" },
      { name: "onTreeLoad", title: "树节点懒加载" },
      { name: "onLoadNode", title: "节点加载" },
      { name: "onLoadSearchData", title: "搜索数据加载" },
      { name: "onSelectChange", title: "选中变化" },
      { name: "onClear", title: "清空" },
      { name: "onReload", title: "刷新" },
      { name: "onValueTreeRender", title: "树值渲染" },
      { name: "onValueListRender", title: "列表值渲染" },
    ],
  },
  {
    renderType: "FormItem",
    name: "表单项",
    group: "form",
    category: "other",
    scaffold: { renderType: "FormItem", label: "标签", prop: "", labelWidth: "", required: false, error: "", showMessage: true, inlineMessage: false, size: "", defaultSlot: null },
    props: [
      { name: "label", title: "标签", propType: "string", defaultValue: "标签" },
      { name: "prop", title: "校验字段名", propType: "string", defaultValue: "" },
      { name: "labelWidth", title: "标签宽度", propType: "string", defaultValue: "" },
      { name: "required", title: "必填", propType: "boolean", defaultValue: false },
      { name: "rules", title: "校验规则", propType: "json", defaultValue: undefined },
      { name: "error", title: "错误信息", propType: "string", defaultValue: "" },
      { name: "showMessage", title: "显示校验信息", propType: "boolean", defaultValue: true },
      { name: "inlineMessage", title: "行内校验信息", propType: "boolean", defaultValue: false },
      { name: "size", title: "尺寸", propType: SIZE_ENUM, defaultValue: "" },
    ],
    events: [],
  },
  {
    renderType: "YqFilterItem",
    name: "筛选项",
    group: "form",
    category: "other",
    scaffold: { renderType: "YqFilterItem", label: "筛选", labelWidth: "", labelPosition: "right", size: "base", description: false, layout: { xs: 24, sm: 12, md: 8, lg: 6, xl: 4 }, defaultSlot: null },
    props: [
      { name: "label", title: "标签", propType: "string", defaultValue: "筛选" },
      { name: "labelWidth", title: "标签宽度", propType: "string", defaultValue: "" },
      {
        name: "labelPosition",
        title: "标签位置",
        propType: { type: "oneOf", value: ["left", "right"], labels: ["左", "右"] },
        defaultValue: "right",
      },
      {
        name: "size",
        title: "尺寸",
        propType: { type: "oneOf", value: ["base", "small", "large"], labels: ["常规", "小", "大"] },
        defaultValue: "base",
      },
      { name: "description", title: "显示说明", propType: "boolean", defaultValue: false },
      { name: "layout", title: "响应式布局", propType: "json", defaultValue: { xs: 24, sm: 12, md: 8, lg: 6, xl: 4 } },
    ],
    events: [
      { name: "onMounted", title: "挂载后" },
      { name: "onChange", title: "值变化" },
      { name: "onValueRender", title: "值渲染" },
    ],
  },
];
